name: Build Manylinux Wheels

on:
  push:
    tags:
      - 'v*'

jobs:
  build-manylinux:
    name: Build manylinux wheels
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["cp310", "cp311", "cp312"]
        
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Build in manylinux container
      run: |
        docker run --rm -v ${{ github.workspace }}:/io \
          quay.io/pypa/manylinux_2_28_x86_64 \
          /bin/bash -c "
            # Install system dependencies
            yum install -y cmake3 || yum install -y cmake
            
            # Install and build pybind11
            cd /tmp
            git clone https://github.com/pybind/pybind11.git
            cd pybind11
            mkdir build && cd build
            cmake .. -DPYBIND11_TEST=OFF
            make -j4
            make install
            
            # Build the wheel for specific Python version
            cd /io
            /opt/python/${{ matrix.python }}-${{ matrix.python }}/bin/pip install numpy wheel
            /opt/python/${{ matrix.python }}-${{ matrix.python }}/bin/python setup.py bdist_wheel
            
            # Audit the wheel to make it manylinux compatible
            auditwheel repair dist/*.whl -w /io/wheelhouse/
          "
    
    - name: Upload wheels
      uses: actions/upload-artifact@v4
      with:
        name: wheels-${{ matrix.python }}
        path: wheelhouse/*.whl

  publish:
    name: Publish to PyPI
    needs: build-manylinux
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Download all wheels
      uses: actions/download-artifact@v4
      with:
        pattern: wheels-*
        path: dist/
        merge-multiple: true
    
    - name: Build source distribution
      run: |
        pip install build
        python -m build --sdist
    
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
        skip-existing: true